
export const PROJECT_CATEGORIES = [
  "Accelerator",
  "Advertising",
  "AI",
  "Alchemy Ecosystem",
  "Aleo Ecosystem",
  "Algorand",
  "AMMM",
  "Analytics",
  "API",
  "Aptos Ecosystem",
  "AR/VR",
  "Arbitrum Ecosystem",
  "Art",
  "Arweave Ecosystem",
  "Asset Management",
  "Audit",
  "Aurora Ecosystem",
  "Avalanche Ecosystem",
  "Babylon Ecosystem",
  "Base Ecosystem",
  "Berachain Ecosystem",
  "Bitcoin Ecosystem",
  "Bittensor Ecosystem",
  "Blast Ecosystem",
  "Blockchain",
  "BNB Chain Ecosystem",
  "Bounty",
  "Cardano Ecosystem",
  "Celo Ecosystem",
  "CEX",
  "Chillz Ecosystem",
  "Communication",
  "Concordium Ecosystem",
  "Cosmos Ecosystem",
  "Cow Cow Ecosystem",
  "CRM ",
  "Cronos Ecosystem",
  "Curve Ecosystem",
  "CyberConnect Ecosystem",
  "Dapp",
  "Defi",
  "DePin",
  "Derivatives",
  "DEX",
  "Eclipse Ecosystem",
  "Education",
  "Elrond Ecosystem",
  "Entertainment/Travel",
  "EOS Ecosystem",
  "Ethereum Ecosystem",
  "Fantom Ecosystem",
  "Finance/Banking",
  "Flow Ecosystem",
  "Flue Ecosystem",
  "Gambling and Betting",
  "Gaming",
  "Gnosis Ecosystem",
  "Heco Ecosystem",
  "Hedera Ecosystem",
  "Hyperliquid Ecosystem",
  "Identify",
  "Immutable Ecosystem",
  "Infrastructure",
  "Initia Ecosystem",
  "Injective Ecosystem",
  "Insurance",
  "Interoperability",
  "IOT",
  "L.0",
  "L.1",
  "L.2",
  "L.3",
  "Lauchpad",
  "LayerZero Ecosystem",
  "Lending/Borrowing",
  "Lens Protocol Ecosystem",
  "Library",
  "Linea Ecosystem",
  "Liquidity",
  "M2E",
  "Mante Ecosystem",
  "Mantle Ecosystem",
  "Marketplace",
  "Media",
  "MegaETH Ecosystem",
  "Meme",
  "Merlin Chain Ecosystem",
  "Metaverse",
  "MEV",
  "Monad Ecosystem",
  "Movement Ecosystem",
  "Multichain",
  "MultivserseX Ecosystem",
  "Music",
  "Near Ecosystem",
  "NFT",
  "Notfication",
  "opBNB Ecosystem",
  "Optimism Ecosystem",
  "Oracle",
  "P2E",
  "Payemnt",
  "Peaq Ecosystem",
  "Polkadot Ecosystem",
  "Polygon Ecosystem",
  "Portfolio Ecosystem",
  "Prediction Markets",
  "Privacy",
  "Real-World Assets",
  "Ronin Ecosystem",
  "Scroll Ecosystem",
  "Security",
  "Sei Ecosystem",
  "Smart Contract Platform",
  "Social Network",
  "Software Development",
  "Solana Ecosystem",
  "Solvency",
  "Soneium Ecosystem",
  "Sonic Ecosystem",
  "Sports",
  "Stablecoin",
  "Stacks Ecosystem",
  "Staking",
  "Starknet Ecosystem",
  "Storage",
  "Story Ecosystem",
  "Sui Ecosystem",
  "Synthetic Issuer",
  "Tax and Accounting",
  "Terra Ecosystem",
  "Tezos Ecosystem",
  "Ton Ecosystem",
  "Trading",
  "TRON Ecosystem",
  "UTXO Ecosystem",
  "Video",
  "Wallet",
  "Wax Ecosystem",
  "Wrapped Tokens",
  "xDAI Ecosystem",
  "XION Ecosystem",
  "XRPL Ecosystem",
  "Yield Aggregator",
  "Zero Knowledge",
  "Zircuit Ecosystem",
  "ZkSync Ecosystem",
]

export const ROUND_TYPES = [
  "Strategic",
  "Unknown",
  "Pre-Seed",
  "Seed",
  "Series A",
  "Series B",
  "Series C",
  "Series D",
  "Series E",
  "Series F",
  "Grants",
  "M&A",
  "Public sale",
  "Private",
  "Angel",
  "IPO",

]

export const formLabelClasses = "block text-sm font-medium mb-1.5 text-foreground";

export const ITEMS_PER_PAGE = 10


export const badgeVariants = [
    "bg-blue-50 text-blue-700 border border-blue-200 dark:bg-blue-900/20 dark:text-blue-300 dark:border-blue-700",
    "bg-green-50 text-green-700 border border-green-200 dark:bg-green-900/20 dark:text-green-300 dark:border-green-700",
    "bg-purple-50 text-purple-700 border border-purple-200 dark:bg-purple-900/20 dark:text-purple-300 dark:border-purple-700",
    "bg-orange-50 text-orange-700 border border-orange-200 dark:bg-orange-900/20 dark:text-orange-300 dark:border-orange-700",
    "bg-teal-50 text-teal-700 border border-teal-200 dark:bg-teal-900/20 dark:text-teal-300 dark:border-teal-700",
    "bg-indigo-50 text-indigo-700 border border-indigo-200 dark:bg-indigo-900/20 dark:text-indigo-300 dark:border-indigo-700",
  ];

export const DROOMDROOM_APP_URL = "https://droomdroom.com";